import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

export const revalidate = 3600 // revalidate at most every hour.

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: `Julián Salvá's Portafolio`,
    description: 'Generated by Next + Sanity',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}
