import { getPages } from '@/sanity/sanity-utils'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

export const revalidate = 3600 // revalidate at most every hour.

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: `Julián Salvá's Portafolio`,
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-5xl mx-auto p-10">
        <header className='flex items-center justify-between border-b-2'>
          <Link
            href="/"
            className="text-4xl font-bold hover:text-green-700 bg-gradient-to-r from-blue-900 via-green-700 to-slate-700 bg-clip-text text-transparent transition-all"
          >Julián
          </Link>
          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page) => {
              return (
                <Link key={page._id} href={`/${page.slug}`} className='hover:scale-105 hover:text-blue-800 text-xl transition-all' >
                  { page.title }
                </Link>
          )
            })}
        </div>
      </header>
      <main className='py-10'>{children}</main>
    </body>
    </html >
  )
}
